title: Scraper
description: >-
  This add-on will scrape and optionally crawl a given site for documents to upload
  to DocumentCloud.  It can also alert you of given keywords appearing in those
  documents.
type: object
properties:
  site:
    type: string
    format: uri
    description: The URL of the site to start scraping
    default: https://docs.google.com/spreadsheets/d/e/2PACX-1vRMANjkxM-a_Uj0beRoq-_LmWou2pE6o061GNvTU9bbfSy-5nzBy1efCMB-vnRCx-cHnboAdqkIDQzL/pubhtml
  project:
    type: number
    description: >-
      The DocumentCloud project ID of the project the documents should be uploaded in to
    default: 208680
  keywords:
    type: array
    items:
      type: string
    description: Keywords to search and notify on
    default:
  filetypes:
    type: array
    items:
      type: string
    description: File extensions to be uploaded to DocumentCloud
    default: 
  crawl_depth:
    type: number
    description: How many pages away from the first site to scrape from
    default: 2
  dry_run:
    type: boolean
    description: Do not upload any documents or store any scraping data
    default: false
    
